package:
  name: golang
  version: 1.4.2

source:
  url: https://storage.googleapis.com/golang/go1.4.2.src.tar.gz
  fn: go1.4.2.src.tar.gz

build:
  number: 0
  detect_binary_files_with_prefix: true

